Release/1.0.0
williamrolando88/world-covid-tracker pull request #5
Opened 2022-02-03 22:07 UTC by williamrolando88

Hi, in this PR, I:
- Installed the required dependencies for the covid tracker project
- Setup the storage with redux-toolkit
- Fetch information from the external database and store it into redux storage
- Created the required components i.e. HomePage, Country
- Setup the routes management to generate unique paths for each country
- Show the 'fetched' information in an appealing way
- Style project according to Behance template.
- Test the whole app to show and to behave as expected

2022-02-03 22:41 UTC, rukundoeric requested changes
Hi @williamrolando88, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-03 22:41 UTC, rukundoeric commented on src/components/Country.js
> +  // onShowData: PropTypes.func.isRequired,
- [ ] <b>REQUIRED:</b> To make sure that your codebase is always clean, remember to remove commented-codes.

2022-02-03 22:41 UTC, rukundoeric commented on src/__tests__/TodayDetail.test.js
> +});
- [ ] <b>REQUIRED:</b> Your tests are failing, kindly fix them. and I really recommend adding more tests cases, you only focused on snapshots and that is not enough. Kindly add more unit tests.

![Screen Shot 2022-02-04 at 00 28 27](https://user-images.githubusercontent.com/45217364/152441303-20bf3f2e-4ddb-40e7-bb1f-e5b2a5b62b8e.png)

2022-02-03 22:41 UTC, rukundoeric commented on src/App.js
> +  );
- [ ] <b>REQUIRED:</b> Your app could not stop loading due to this error in the image below:
![Screen Shot 2022-02-04 at 00 28 15](https://user-images.githubusercontent.com/45217364/152441129-0adaac09-2c8c-4838-939e-facdce789742.png)
Kindly address the issue and fix it.

2022-02-03 23:29 UTC, williamrolando88 commented on src/App.js
> +  );
I was due to the different time zone

2022-02-04 00:33 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @williamrolando88,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
#### _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 00:33 UTC, TedLivist commented on src/components/Country.js
> +  // onShowData: PropTypes.func.isRequired,
- [ ] You are yet to remove the commented code as highlighted by the previous reviewer. Kindly remove it.

2022-02-04 00:33 UTC, TedLivist commented on src/__tests__/Redux.test.js
> +// const dispatch = useDispatch();
- [ ] Your new file contains commented code. Kindly remove it. It makes your codebase look messy.

2022-02-04 00:33 UTC, TedLivist commented on src/__tests__/TodayDetail.test.js
> +  });
- [ ] One of your tests is still failing, specifically this one. **NOTE:** I updated the snapshot tests as suggested in your additional info message.

2022-02-04 04:12 UTC, williamrolando88 commented on src/components/Country.js
> +  // onShowData: PropTypes.func.isRequired,
I'm pretty sure I previously solved

2022-02-04 04:25 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi William, 

Your project is complete! Great job for making the necessary changes recommended in the previous review. There is nothing else to say other than... it's time to merge it 🍾 :shipit:. Congratulations! 🎉🥂

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider my comment(s) marked **[OPTIONAL]** under this review:_
<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-04 04:25 UTC, rloterh commented on src/components/HomePage.js
> +  /* eslint-disable */
- [ ] OPTIONAL
You have **disabled linter check** on your code. Please enable linter check on your code to ensure that your code is robust code and clean.

2022-02-04 14:11 UTC, merged